// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_token.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_token (garden_id, name, token_hash, prefix, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, garden_id, name, token_hash, prefix, created_by, created_at, expires_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	GardenID  uuid.UUID
	Name      string
	TokenHash string
	Prefix    string
	CreatedBy uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (APIToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.GardenID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i APIToken
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, garden_id, name, token_hash, prefix, created_by, created_at, expires_at, last_used_at, revoked_at FROM api_token WHERE token_hash = $1
`

// Returns revoked and expired rows too, so the caller decides whether the
// token still works. It binds no garden_id because this row is what tells a
// request which garden it is on.
func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (APIToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i APIToken
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, garden_id, name, token_hash, prefix, created_by, created_at, expires_at, last_used_at, revoked_at FROM api_token
WHERE garden_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC, id
`

// The Tokens list, newest first. A revoked token leaves the list. One that has
// expired stays in it and goes grey, because it is still the row somebody came
// looking for.
func (q *Queries) ListAPITokens(ctx context.Context, gardenID uuid.UUID) ([]APIToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens, gardenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIToken
	for rows.Next() {
		var i APIToken
		if err := rows.Scan(
			&i.ID,
			&i.GardenID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokenDeadlines = `-- name: ListTokenDeadlines :many
SELECT api_token.id, api_token.garden_id, api_token.name, api_token.token_hash, api_token.prefix, api_token.created_by, api_token.created_at, api_token.expires_at, api_token.last_used_at, api_token.revoked_at, membership.id AS membership_id, membership.user_id,
    app_user.handle, app_user.timezone, garden.name AS garden_name,
    coalesce(owner.display_name, '')::text AS owner_name,
    coalesce(owner.id = membership.user_id, false)::boolean AS recipient_owns
FROM api_token
JOIN garden ON garden.id = api_token.garden_id
JOIN membership ON membership.garden_id = api_token.garden_id
    AND (membership.expires_at IS NULL OR membership.expires_at > $1::timestamptz)
JOIN role_capability ON role_capability.role = membership.role AND role_capability.capability = $2
JOIN app_user ON app_user.id = membership.user_id
LEFT JOIN LATERAL (
    SELECT app_user.id, app_user.display_name
    FROM membership o
    JOIN app_user ON app_user.id = o.user_id
    WHERE o.garden_id = garden.id AND o.role = 'owner'
    ORDER BY o.created_at, o.id
    LIMIT 1
) AS owner ON true
WHERE api_token.revoked_at IS NULL
  AND api_token.expires_at > $3::timestamptz
  AND EXISTS (SELECT 1 FROM push_subscription WHERE push_subscription.user_id = membership.user_id)
ORDER BY api_token.expires_at, api_token.id, membership.created_at, membership.id
`

type ListTokenDeadlinesParams struct {
	Now        time.Time
	Capability string
	Since      time.Time
}

type ListTokenDeadlinesRow struct {
	APIToken      APIToken
	MembershipID  uuid.UUID
	UserID        uuid.UUID
	Handle        string
	Timezone      string
	GardenName    string
	OwnerName     string
	RecipientOwns bool
}

// Every unrevoked token expiring after @since, paired with each member of its
// garden whose role grants @capability and whose membership has not ended at
// @now. A member with no browser subscribed is left out, so the job never
// claims a ledger row and then sends nothing. owner_name is the garden's
// owner's display name, or empty when no owner is left, and recipient_owns is
// whether the member is that owner. There is no @garden_id because the job
// runs across every garden.
func (q *Queries) ListTokenDeadlines(ctx context.Context, arg ListTokenDeadlinesParams) ([]ListTokenDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, listTokenDeadlines, arg.Now, arg.Capability, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTokenDeadlinesRow
	for rows.Next() {
		var i ListTokenDeadlinesRow
		if err := rows.Scan(
			&i.APIToken.ID,
			&i.APIToken.GardenID,
			&i.APIToken.Name,
			&i.APIToken.TokenHash,
			&i.APIToken.Prefix,
			&i.APIToken.CreatedBy,
			&i.APIToken.CreatedAt,
			&i.APIToken.ExpiresAt,
			&i.APIToken.LastUsedAt,
			&i.APIToken.RevokedAt,
			&i.MembershipID,
			&i.UserID,
			&i.Handle,
			&i.Timezone,
			&i.GardenName,
			&i.OwnerName,
			&i.RecipientOwns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_token SET revoked_at = $1::timestamptz
WHERE garden_id = $2 AND id = $3 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	Now      time.Time
	GardenID uuid.UUID
	TokenID  uuid.UUID
}

// Revoke and Remove are one write. The row leaves the list either way, and the
// two words differ because one stops a credential that still works and the
// other clears away one that has already run out.
func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.Now, arg.GardenID, arg.TokenID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_token SET last_used_at = $1::timestamptz WHERE token_hash = $2
`

func (q *Queries) TouchAPIToken(ctx context.Context, now time.Time, tokenHash string) error {
	_, err := q.db.Exec(ctx, touchAPIToken, now, tokenHash)
	return err
}
