// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_user.sql

package store

import (
	"context"

	"uuid"
)

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, display_name, handle, timezone, created_at FROM app_user
WHERE handle = $1
`

func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByHandle, handle)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Handle,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, display_name, handle, timezone, created_at FROM app_user
ORDER BY created_at, id
`

// Both queries exist for the development sign-in, which lists every user and
// signs one in by handle alone. Nothing in a production build calls them, and
// they will be removed with the development sign-in.
func (q *Queries) ListUsers(ctx context.Context) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppUser
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Handle,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :exec
UPDATE app_user
SET display_name = $1, handle = $2, timezone = $3
WHERE id = $4
`

type UpdateAccountParams struct {
	DisplayName string
	Handle      string
	Timezone    string
	UserID      uuid.UUID
}

// Nothing checks that the handle is free before this runs. The unique index on
// app_user.handle rejects a duplicate. A check made first would let two
// accounts saving the same handle at the same moment both pass it.
func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) error {
	_, err := q.db.Exec(ctx, updateAccount,
		arg.DisplayName,
		arg.Handle,
		arg.Timezone,
		arg.UserID,
	)
	return err
}
