// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_user.sql

package store

import (
	"context"
)

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, display_name, handle, timezone, created_at FROM app_user
WHERE handle = $1
`

func (q *Queries) GetUserByHandle(ctx context.Context, handle string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByHandle, handle)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Handle,
		&i.Timezone,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, display_name, handle, timezone, created_at FROM app_user
ORDER BY created_at, id
`

// Both reads exist for the development sign-in, which offers every user and
// takes a handle as the whole credential. Nothing in a production build calls
// them, and they go when the development sign-in does.
func (q *Queries) ListUsers(ctx context.Context) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppUser
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Handle,
			&i.Timezone,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
