// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar_note.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createCalendarNote = `-- name: CreateCalendarNote :one
INSERT INTO calendar_note (garden_id, starts_on, ends_on, text, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, garden_id, starts_on, ends_on, text, created_by, created_at
`

type CreateCalendarNoteParams struct {
	GardenID  uuid.UUID
	StartsOn  time.Time
	EndsOn    time.Time
	Text      string
	CreatedBy uuid.UUID
}

func (q *Queries) CreateCalendarNote(ctx context.Context, arg CreateCalendarNoteParams) (CalendarNote, error) {
	row := q.db.QueryRow(ctx, createCalendarNote,
		arg.GardenID,
		arg.StartsOn,
		arg.EndsOn,
		arg.Text,
		arg.CreatedBy,
	)
	var i CalendarNote
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.StartsOn,
		&i.EndsOn,
		&i.Text,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCalendarNote = `-- name: DeleteCalendarNote :one
DELETE FROM calendar_note
WHERE garden_id = $1 AND id = $2
RETURNING id
`

func (q *Queries) DeleteCalendarNote(ctx context.Context, gardenID uuid.UUID, noteID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCalendarNote, gardenID, noteID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCalendarNote = `-- name: GetCalendarNote :one
SELECT id, garden_id, starts_on, ends_on, text, created_by, created_at FROM calendar_note
WHERE garden_id = $1 AND id = $2
`

func (q *Queries) GetCalendarNote(ctx context.Context, gardenID uuid.UUID, noteID uuid.UUID) (CalendarNote, error) {
	row := q.db.QueryRow(ctx, getCalendarNote, gardenID, noteID)
	var i CalendarNote
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.StartsOn,
		&i.EndsOn,
		&i.Text,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listCalendarNotesBetween = `-- name: ListCalendarNotesBetween :many
SELECT id, garden_id, starts_on, ends_on, text, created_by, created_at FROM calendar_note
WHERE garden_id = $1 AND starts_on <= $2 AND ends_on >= $3
ORDER BY starts_on, created_at, id
`

type ListCalendarNotesBetweenParams struct {
	GardenID uuid.UUID
	Until    time.Time
	Since    time.Time
}

// The notes with a day in the range, earliest start first. @since and @until
// are the first and last day of the range, both included.
func (q *Queries) ListCalendarNotesBetween(ctx context.Context, arg ListCalendarNotesBetweenParams) ([]CalendarNote, error) {
	rows, err := q.db.Query(ctx, listCalendarNotesBetween, arg.GardenID, arg.Until, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarNote
	for rows.Next() {
		var i CalendarNote
		if err := rows.Scan(
			&i.ID,
			&i.GardenID,
			&i.StartsOn,
			&i.EndsOn,
			&i.Text,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarNote = `-- name: UpdateCalendarNote :one
UPDATE calendar_note SET starts_on = $1, ends_on = $2, text = $3
WHERE garden_id = $4 AND id = $5
RETURNING id, garden_id, starts_on, ends_on, text, created_by, created_at
`

type UpdateCalendarNoteParams struct {
	StartsOn time.Time
	EndsOn   time.Time
	Text     string
	GardenID uuid.UUID
	NoteID   uuid.UUID
}

func (q *Queries) UpdateCalendarNote(ctx context.Context, arg UpdateCalendarNoteParams) (CalendarNote, error) {
	row := q.db.QueryRow(ctx, updateCalendarNote,
		arg.StartsOn,
		arg.EndsOn,
		arg.Text,
		arg.GardenID,
		arg.NoteID,
	)
	var i CalendarNote
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.StartsOn,
		&i.EndsOn,
		&i.Text,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
