// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: care_type.sql

package store

import (
	"context"

	"uuid"
)

const listCareTypes = `-- name: ListCareTypes :many
SELECT id, garden_id, name, slug, created_at, archived_at FROM care_type
WHERE garden_id = $1 AND archived_at IS NULL
ORDER BY created_at
`

// Care types are listed in creation order.
func (q *Queries) ListCareTypes(ctx context.Context, gardenID uuid.UUID) ([]CareType, error) {
	rows, err := q.db.Query(ctx, listCareTypes, gardenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareType
	for rows.Next() {
		var i CareType
		if err := rows.Scan(
			&i.ID,
			&i.GardenID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
