// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: care_event.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createCareEvent = `-- name: CreateCareEvent :one
INSERT INTO care_event (garden_id, plant_id, care_type_id, performed_by, performed_at, recorded_at, done, note, override_interval_days)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, garden_id, plant_id, care_type_id, performed_by, performed_at, recorded_at, done, note, override_interval_days
`

type CreateCareEventParams struct {
	GardenID             uuid.UUID
	PlantID              uuid.UUID
	CareTypeID           uuid.UUID
	PerformedBy          uuid.UUID
	PerformedAt          time.Time
	RecordedAt           time.Time
	Done                 bool
	Note                 *string
	OverrideIntervalDays *int32
}

// The handler passes recorded_at because its clock and the row have to agree.
func (q *Queries) CreateCareEvent(ctx context.Context, arg CreateCareEventParams) (CareEvent, error) {
	row := q.db.QueryRow(ctx, createCareEvent,
		arg.GardenID,
		arg.PlantID,
		arg.CareTypeID,
		arg.PerformedBy,
		arg.PerformedAt,
		arg.RecordedAt,
		arg.Done,
		arg.Note,
		arg.OverrideIntervalDays,
	)
	var i CareEvent
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.PlantID,
		&i.CareTypeID,
		&i.PerformedBy,
		&i.PerformedAt,
		&i.RecordedAt,
		&i.Done,
		&i.Note,
		&i.OverrideIntervalDays,
	)
	return i, err
}

const deleteCareEvent = `-- name: DeleteCareEvent :one
DELETE FROM care_event
WHERE id = $1 AND garden_id = $2 AND plant_id = $3
  AND ($4::boolean OR performed_by = $5)
RETURNING id, garden_id, plant_id, care_type_id, performed_by, performed_at, recorded_at, done, note, override_interval_days
`

type DeleteCareEventParams struct {
	ID           uuid.UUID
	GardenID     uuid.UUID
	PlantID      uuid.UUID
	MayDeleteAny bool
	PerformedBy  uuid.UUID
}

// DeleteCareEvent matches on performed_by unless may_delete_any is set,
// because a check standing beside the query can be forgotten. Nothing bounds
// how old the event may be because the undo window decides what the feed
// draws rather than what the delete accepts.
func (q *Queries) DeleteCareEvent(ctx context.Context, arg DeleteCareEventParams) (CareEvent, error) {
	row := q.db.QueryRow(ctx, deleteCareEvent,
		arg.ID,
		arg.GardenID,
		arg.PlantID,
		arg.MayDeleteAny,
		arg.PerformedBy,
	)
	var i CareEvent
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.PlantID,
		&i.CareTypeID,
		&i.PerformedBy,
		&i.PerformedAt,
		&i.RecordedAt,
		&i.Done,
		&i.Note,
		&i.OverrideIntervalDays,
	)
	return i, err
}

const listCareEventLog = `-- name: ListCareEventLog :many
SELECT care_event.id, care_event.garden_id, care_event.plant_id, care_event.care_type_id, care_event.performed_by, care_event.performed_at, care_event.recorded_at, care_event.done, care_event.note, care_event.override_interval_days, plant.id, plant.garden_id, plant.nickname, plant.common_name, plant.botanical_name, plant.location, plant.sun, plant.water_needs, plant.feed_needs, plant.soil, plant.climate, plant.pot, plant.notes, plant.acquired_year, plant.acquired_month, plant.created_at, plant.archived_at, care_type.id, care_type.garden_id, care_type.name, care_type.slug, care_type.created_at, care_type.archived_at, app_user.display_name AS performed_by_name
FROM care_event
JOIN plant ON plant.id = care_event.plant_id AND plant.garden_id = care_event.garden_id
JOIN care_type ON care_type.id = care_event.care_type_id AND care_type.garden_id = care_event.garden_id
JOIN app_user ON app_user.id = care_event.performed_by
WHERE care_event.garden_id = $1
  AND ($2::uuid IS NULL OR care_event.plant_id = $2)
  AND ($3::timestamptz IS NULL
       OR (care_event.performed_at, care_event.id) < ($3, $4::uuid))
ORDER BY care_event.performed_at DESC, care_event.id DESC
LIMIT $5
`

type ListCareEventLogParams struct {
	GardenID uuid.UUID
	PlantID  *uuid.UUID
	BeforeAt *time.Time
	BeforeID *uuid.UUID
	Count    int32
}

type ListCareEventLogRow struct {
	CareEvent       CareEvent
	Plant           Plant
	CareType        CareType
	PerformedByName string
}

// ListCareEventLog reads one page of Activity. It orders by performed_at rather
// than recorded_at because the page dates an event by when the care happened,
// not by when it was entered.
//
// plant_id is null for the whole garden, or a plant id to show only that plant.
//
// before_at and before_id are null for the newest page, and otherwise hold the
// performed_at and id of the last event on the previous page. Both columns are
// compared because backdated events can share a performed_at to the minute.
func (q *Queries) ListCareEventLog(ctx context.Context, arg ListCareEventLogParams) ([]ListCareEventLogRow, error) {
	rows, err := q.db.Query(ctx, listCareEventLog,
		arg.GardenID,
		arg.PlantID,
		arg.BeforeAt,
		arg.BeforeID,
		arg.Count,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCareEventLogRow
	for rows.Next() {
		var i ListCareEventLogRow
		if err := rows.Scan(
			&i.CareEvent.ID,
			&i.CareEvent.GardenID,
			&i.CareEvent.PlantID,
			&i.CareEvent.CareTypeID,
			&i.CareEvent.PerformedBy,
			&i.CareEvent.PerformedAt,
			&i.CareEvent.RecordedAt,
			&i.CareEvent.Done,
			&i.CareEvent.Note,
			&i.CareEvent.OverrideIntervalDays,
			&i.Plant.ID,
			&i.Plant.GardenID,
			&i.Plant.Nickname,
			&i.Plant.CommonName,
			&i.Plant.BotanicalName,
			&i.Plant.Location,
			&i.Plant.Sun,
			&i.Plant.WaterNeeds,
			&i.Plant.FeedNeeds,
			&i.Plant.Soil,
			&i.Plant.Climate,
			&i.Plant.Pot,
			&i.Plant.Notes,
			&i.Plant.AcquiredYear,
			&i.Plant.AcquiredMonth,
			&i.Plant.CreatedAt,
			&i.Plant.ArchivedAt,
			&i.CareType.ID,
			&i.CareType.GardenID,
			&i.CareType.Name,
			&i.CareType.Slug,
			&i.CareType.CreatedAt,
			&i.CareType.ArchivedAt,
			&i.PerformedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestCareEvents = `-- name: ListLatestCareEvents :many
SELECT DISTINCT ON (plant_id, care_type_id) id, garden_id, plant_id, care_type_id, performed_by, performed_at, recorded_at, done, note, override_interval_days
FROM care_event
WHERE garden_id = $1
ORDER BY plant_id, care_type_id, performed_at DESC
`

// A skipped event is a plant's latest one too, so nothing here filters on done.
// An event whose plant or care type was archived stays in, because the caller
// pairs these rows against ListCareSchedules, which already excludes both.
func (q *Queries) ListLatestCareEvents(ctx context.Context, gardenID uuid.UUID) ([]CareEvent, error) {
	rows, err := q.db.Query(ctx, listLatestCareEvents, gardenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareEvent
	for rows.Next() {
		var i CareEvent
		if err := rows.Scan(
			&i.ID,
			&i.GardenID,
			&i.PlantID,
			&i.CareTypeID,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.RecordedAt,
			&i.Done,
			&i.Note,
			&i.OverrideIntervalDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantCareEvents = `-- name: ListPlantCareEvents :many
SELECT care_event.id, care_event.garden_id, care_event.plant_id, care_event.care_type_id, care_event.performed_by, care_event.performed_at, care_event.recorded_at, care_event.done, care_event.note, care_event.override_interval_days, care_type.id, care_type.garden_id, care_type.name, care_type.slug, care_type.created_at, care_type.archived_at, app_user.display_name AS performed_by_name
FROM care_event
JOIN care_type ON care_type.id = care_event.care_type_id AND care_type.garden_id = care_event.garden_id
JOIN app_user ON app_user.id = care_event.performed_by
WHERE care_event.garden_id = $1 AND care_event.plant_id = $2
ORDER BY care_event.performed_at DESC, care_event.id DESC
LIMIT $3
`

type ListPlantCareEventsParams struct {
	GardenID uuid.UUID
	PlantID  uuid.UUID
	Count    int32
}

type ListPlantCareEventsRow struct {
	CareEvent       CareEvent
	CareType        CareType
	PerformedByName string
}

// The order is performed_at because a plant's Recent is a history of the plant
// rather than of what was typed. Nothing here joins plant, because the page is
// the plant.
func (q *Queries) ListPlantCareEvents(ctx context.Context, arg ListPlantCareEventsParams) ([]ListPlantCareEventsRow, error) {
	rows, err := q.db.Query(ctx, listPlantCareEvents, arg.GardenID, arg.PlantID, arg.Count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlantCareEventsRow
	for rows.Next() {
		var i ListPlantCareEventsRow
		if err := rows.Scan(
			&i.CareEvent.ID,
			&i.CareEvent.GardenID,
			&i.CareEvent.PlantID,
			&i.CareEvent.CareTypeID,
			&i.CareEvent.PerformedBy,
			&i.CareEvent.PerformedAt,
			&i.CareEvent.RecordedAt,
			&i.CareEvent.Done,
			&i.CareEvent.Note,
			&i.CareEvent.OverrideIntervalDays,
			&i.CareType.ID,
			&i.CareType.GardenID,
			&i.CareType.Name,
			&i.CareType.Slug,
			&i.CareType.CreatedAt,
			&i.CareType.ArchivedAt,
			&i.PerformedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCareEvents = `-- name: ListRecentCareEvents :many
SELECT care_event.id, care_event.garden_id, care_event.plant_id, care_event.care_type_id, care_event.performed_by, care_event.performed_at, care_event.recorded_at, care_event.done, care_event.note, care_event.override_interval_days, plant.id, plant.garden_id, plant.nickname, plant.common_name, plant.botanical_name, plant.location, plant.sun, plant.water_needs, plant.feed_needs, plant.soil, plant.climate, plant.pot, plant.notes, plant.acquired_year, plant.acquired_month, plant.created_at, plant.archived_at, care_type.id, care_type.garden_id, care_type.name, care_type.slug, care_type.created_at, care_type.archived_at, app_user.display_name AS performed_by_name
FROM care_event
JOIN plant ON plant.id = care_event.plant_id AND plant.garden_id = care_event.garden_id
JOIN care_type ON care_type.id = care_event.care_type_id AND care_type.garden_id = care_event.garden_id
JOIN app_user ON app_user.id = care_event.performed_by
WHERE care_event.garden_id = $1
ORDER BY care_event.recorded_at DESC, care_event.id DESC
LIMIT $2
`

type ListRecentCareEventsRow struct {
	CareEvent       CareEvent
	Plant           Plant
	CareType        CareType
	PerformedByName string
}

// The order is recorded_at rather than performed_at so a backdated care still
// lands at the top of the feed.
func (q *Queries) ListRecentCareEvents(ctx context.Context, gardenID uuid.UUID, count int32) ([]ListRecentCareEventsRow, error) {
	rows, err := q.db.Query(ctx, listRecentCareEvents, gardenID, count)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentCareEventsRow
	for rows.Next() {
		var i ListRecentCareEventsRow
		if err := rows.Scan(
			&i.CareEvent.ID,
			&i.CareEvent.GardenID,
			&i.CareEvent.PlantID,
			&i.CareEvent.CareTypeID,
			&i.CareEvent.PerformedBy,
			&i.CareEvent.PerformedAt,
			&i.CareEvent.RecordedAt,
			&i.CareEvent.Done,
			&i.CareEvent.Note,
			&i.CareEvent.OverrideIntervalDays,
			&i.Plant.ID,
			&i.Plant.GardenID,
			&i.Plant.Nickname,
			&i.Plant.CommonName,
			&i.Plant.BotanicalName,
			&i.Plant.Location,
			&i.Plant.Sun,
			&i.Plant.WaterNeeds,
			&i.Plant.FeedNeeds,
			&i.Plant.Soil,
			&i.Plant.Climate,
			&i.Plant.Pot,
			&i.Plant.Notes,
			&i.Plant.AcquiredYear,
			&i.Plant.AcquiredMonth,
			&i.Plant.CreatedAt,
			&i.Plant.ArchivedAt,
			&i.CareType.ID,
			&i.CareType.GardenID,
			&i.CareType.Name,
			&i.CareType.Slug,
			&i.CareType.CreatedAt,
			&i.CareType.ArchivedAt,
			&i.PerformedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
