// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: care_schedule.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createCareSchedule = `-- name: CreateCareSchedule :one
INSERT INTO care_schedule (garden_id, plant_id, care_type_id, interval_count, interval_unit,
                           anchor_date, anchor_precision, season_start_month, season_end_month)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
RETURNING id, garden_id, plant_id, care_type_id, interval_count, interval_unit, anchor_date, anchor_precision, season_start_month, season_end_month, set_at
`

type CreateCareScheduleParams struct {
	GardenID         uuid.UUID
	PlantID          uuid.UUID
	CareTypeID       uuid.UUID
	IntervalCount    *int32
	IntervalUnit     *string
	AnchorDate       *time.Time
	AnchorPrecision  *string
	SeasonStartMonth *int16
	SeasonEndMonth   *int16
}

// set_at defaults to now, so a plant added today with a ten-day cadence is due
// in ten days rather than overdue on arrival.
func (q *Queries) CreateCareSchedule(ctx context.Context, arg CreateCareScheduleParams) (CareSchedule, error) {
	row := q.db.QueryRow(ctx, createCareSchedule,
		arg.GardenID,
		arg.PlantID,
		arg.CareTypeID,
		arg.IntervalCount,
		arg.IntervalUnit,
		arg.AnchorDate,
		arg.AnchorPrecision,
		arg.SeasonStartMonth,
		arg.SeasonEndMonth,
	)
	var i CareSchedule
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.PlantID,
		&i.CareTypeID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.AnchorDate,
		&i.AnchorPrecision,
		&i.SeasonStartMonth,
		&i.SeasonEndMonth,
		&i.SetAt,
	)
	return i, err
}

const deleteCareSchedule = `-- name: DeleteCareSchedule :one
DELETE FROM care_schedule
WHERE garden_id = $1 AND plant_id = $2 AND care_type_id = $3
RETURNING id
`

type DeleteCareScheduleParams struct {
	GardenID   uuid.UUID
	PlantID    uuid.UUID
	CareTypeID uuid.UUID
}

// The events the schedule produced stay where they are, so the care type drops
// back to being one the plant is not on rather than losing its history.
func (q *Queries) DeleteCareSchedule(ctx context.Context, arg DeleteCareScheduleParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCareSchedule, arg.GardenID, arg.PlantID, arg.CareTypeID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCareSchedules = `-- name: ListCareSchedules :many
SELECT care_schedule.id, care_schedule.garden_id, care_schedule.plant_id, care_schedule.care_type_id, care_schedule.interval_count, care_schedule.interval_unit, care_schedule.anchor_date, care_schedule.anchor_precision, care_schedule.season_start_month, care_schedule.season_end_month, care_schedule.set_at, plant.id, plant.garden_id, plant.nickname, plant.common_name, plant.botanical_name, plant.location, plant.sun, plant.water_needs, plant.feed_needs, plant.soil, plant.climate, plant.pot, plant.notes, plant.acquired_year, plant.acquired_month, plant.created_at, plant.archived_at, care_type.id, care_type.garden_id, care_type.name, care_type.slug, care_type.created_at, care_type.archived_at
FROM care_schedule
JOIN plant ON plant.id = care_schedule.plant_id AND plant.garden_id = care_schedule.garden_id
JOIN care_type ON care_type.id = care_schedule.care_type_id AND care_type.garden_id = care_schedule.garden_id
WHERE care_schedule.garden_id = $1
  AND plant.archived_at IS NULL
  AND care_type.archived_at IS NULL
ORDER BY plant.location NULLS LAST, coalesce(plant.nickname, plant.common_name, plant.botanical_name), plant.id, care_type.created_at, care_type.id
`

type ListCareSchedulesRow struct {
	CareSchedule CareSchedule
	Plant        Plant
	CareType     CareType
}

// Every caller hands these rows to the due-date engine in Go, so no due date
// is computed here. The ordering is the roster's, and id ends it so two
// plants agreeing on room and name keep their order.
func (q *Queries) ListCareSchedules(ctx context.Context, gardenID uuid.UUID) ([]ListCareSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listCareSchedules, gardenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCareSchedulesRow
	for rows.Next() {
		var i ListCareSchedulesRow
		if err := rows.Scan(
			&i.CareSchedule.ID,
			&i.CareSchedule.GardenID,
			&i.CareSchedule.PlantID,
			&i.CareSchedule.CareTypeID,
			&i.CareSchedule.IntervalCount,
			&i.CareSchedule.IntervalUnit,
			&i.CareSchedule.AnchorDate,
			&i.CareSchedule.AnchorPrecision,
			&i.CareSchedule.SeasonStartMonth,
			&i.CareSchedule.SeasonEndMonth,
			&i.CareSchedule.SetAt,
			&i.Plant.ID,
			&i.Plant.GardenID,
			&i.Plant.Nickname,
			&i.Plant.CommonName,
			&i.Plant.BotanicalName,
			&i.Plant.Location,
			&i.Plant.Sun,
			&i.Plant.WaterNeeds,
			&i.Plant.FeedNeeds,
			&i.Plant.Soil,
			&i.Plant.Climate,
			&i.Plant.Pot,
			&i.Plant.Notes,
			&i.Plant.AcquiredYear,
			&i.Plant.AcquiredMonth,
			&i.Plant.CreatedAt,
			&i.Plant.ArchivedAt,
			&i.CareType.ID,
			&i.CareType.GardenID,
			&i.CareType.Name,
			&i.CareType.Slug,
			&i.CareType.CreatedAt,
			&i.CareType.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCareSchedule = `-- name: UpsertCareSchedule :one
INSERT INTO care_schedule (garden_id, plant_id, care_type_id, interval_count, interval_unit,
                           anchor_date, anchor_precision, season_start_month, season_end_month)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
ON CONFLICT (plant_id, care_type_id) DO UPDATE
SET interval_count     = excluded.interval_count,
    interval_unit      = excluded.interval_unit,
    anchor_date        = excluded.anchor_date,
    anchor_precision   = excluded.anchor_precision,
    season_start_month = excluded.season_start_month,
    season_end_month   = excluded.season_end_month,
    set_at             = now()
RETURNING id, garden_id, plant_id, care_type_id, interval_count, interval_unit, anchor_date, anchor_precision, season_start_month, season_end_month, set_at
`

type UpsertCareScheduleParams struct {
	GardenID         uuid.UUID
	PlantID          uuid.UUID
	CareTypeID       uuid.UUID
	IntervalCount    *int32
	IntervalUnit     *string
	AnchorDate       *time.Time
	AnchorPrecision  *string
	SeasonStartMonth *int16
	SeasonEndMonth   *int16
}

// A plant is scheduled for a care type at most once, so saving the editor
// either writes the row or replaces it. set_at moves with the save, which is
// what leaves a schedule newly set with no history due a full interval from
// now and what brings a spent one-off back.
func (q *Queries) UpsertCareSchedule(ctx context.Context, arg UpsertCareScheduleParams) (CareSchedule, error) {
	row := q.db.QueryRow(ctx, upsertCareSchedule,
		arg.GardenID,
		arg.PlantID,
		arg.CareTypeID,
		arg.IntervalCount,
		arg.IntervalUnit,
		arg.AnchorDate,
		arg.AnchorPrecision,
		arg.SeasonStartMonth,
		arg.SeasonEndMonth,
	)
	var i CareSchedule
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.PlantID,
		&i.CareTypeID,
		&i.IntervalCount,
		&i.IntervalUnit,
		&i.AnchorDate,
		&i.AnchorPrecision,
		&i.SeasonStartMonth,
		&i.SeasonEndMonth,
		&i.SetAt,
	)
	return i, err
}
