// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: care_event.sql

package store

import (
	"context"

	"uuid"
)

const listLatestCareEvents = `-- name: ListLatestCareEvents :many
SELECT DISTINCT ON (plant_id, care_type_id) id, garden_id, plant_id, care_type_id, performed_by, performed_at, recorded_at, done, note, override_interval_days
FROM care_event
WHERE garden_id = $1
ORDER BY plant_id, care_type_id, performed_at DESC
`

// A skipped event is a plant's latest one too, so nothing here filters on done.
// An event whose plant or care type was archived stays in, because the caller
// pairs these rows against ListCareSchedules, which already excludes both.
func (q *Queries) ListLatestCareEvents(ctx context.Context, gardenID uuid.UUID) ([]CareEvent, error) {
	rows, err := q.db.Query(ctx, listLatestCareEvents, gardenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CareEvent
	for rows.Next() {
		var i CareEvent
		if err := rows.Scan(
			&i.ID,
			&i.GardenID,
			&i.PlantID,
			&i.CareTypeID,
			&i.PerformedBy,
			&i.PerformedAt,
			&i.RecordedAt,
			&i.Done,
			&i.Note,
			&i.OverrideIntervalDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
