// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: care_schedule.sql

package store

import (
	"context"

	"uuid"
)

const listCareSchedules = `-- name: ListCareSchedules :many
SELECT care_schedule.id, care_schedule.garden_id, care_schedule.plant_id, care_schedule.care_type_id, care_schedule.interval_count, care_schedule.interval_unit, care_schedule.anchor_date, care_schedule.anchor_precision, care_schedule.season_start_month, care_schedule.season_end_month, care_schedule.set_at, plant.id, plant.garden_id, plant.nickname, plant.common_name, plant.botanical_name, plant.location, plant.sun, plant.water_needs, plant.feed_needs, plant.soil, plant.climate, plant.pot, plant.notes, plant.acquired_year, plant.acquired_month, plant.created_at, plant.archived_at, care_type.id, care_type.garden_id, care_type.name, care_type.slug, care_type.created_at, care_type.archived_at
FROM care_schedule
JOIN plant ON plant.id = care_schedule.plant_id AND plant.garden_id = care_schedule.garden_id
JOIN care_type ON care_type.id = care_schedule.care_type_id AND care_type.garden_id = care_schedule.garden_id
WHERE care_schedule.garden_id = $1
  AND plant.archived_at IS NULL
  AND care_type.archived_at IS NULL
ORDER BY plant.location NULLS LAST, coalesce(plant.nickname, plant.common_name, plant.botanical_name), plant.id, care_type.created_at, care_type.id
`

type ListCareSchedulesRow struct {
	CareSchedule CareSchedule
	Plant        Plant
	CareType     CareType
}

// Every caller hands these rows to the due-date engine in Go, so no due date
// is computed here. The ordering is the roster's, and id ends it so two
// plants agreeing on room and name keep their order.
func (q *Queries) ListCareSchedules(ctx context.Context, gardenID uuid.UUID) ([]ListCareSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listCareSchedules, gardenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCareSchedulesRow
	for rows.Next() {
		var i ListCareSchedulesRow
		if err := rows.Scan(
			&i.CareSchedule.ID,
			&i.CareSchedule.GardenID,
			&i.CareSchedule.PlantID,
			&i.CareSchedule.CareTypeID,
			&i.CareSchedule.IntervalCount,
			&i.CareSchedule.IntervalUnit,
			&i.CareSchedule.AnchorDate,
			&i.CareSchedule.AnchorPrecision,
			&i.CareSchedule.SeasonStartMonth,
			&i.CareSchedule.SeasonEndMonth,
			&i.CareSchedule.SetAt,
			&i.Plant.ID,
			&i.Plant.GardenID,
			&i.Plant.Nickname,
			&i.Plant.CommonName,
			&i.Plant.BotanicalName,
			&i.Plant.Location,
			&i.Plant.Sun,
			&i.Plant.WaterNeeds,
			&i.Plant.FeedNeeds,
			&i.Plant.Soil,
			&i.Plant.Climate,
			&i.Plant.Pot,
			&i.Plant.Notes,
			&i.Plant.AcquiredYear,
			&i.Plant.AcquiredMonth,
			&i.Plant.CreatedAt,
			&i.Plant.ArchivedAt,
			&i.CareType.ID,
			&i.CareType.GardenID,
			&i.CareType.Name,
			&i.CareType.Slug,
			&i.CareType.CreatedAt,
			&i.CareType.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
