// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: garden.sql

package store

import (
	"context"

	"uuid"
)

const createGarden = `-- name: CreateGarden :one
INSERT INTO garden (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateGarden(ctx context.Context, name string) (Garden, error) {
	row := q.db.QueryRow(ctx, createGarden, name)
	var i Garden
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteGarden = `-- name: DeleteGarden :execrows
DELETE FROM garden WHERE id = $1
`

func (q *Queries) DeleteGarden(ctx context.Context, gardenID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGarden, gardenID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGardenCareEvents = `-- name: DeleteGardenCareEvents :exec
DELETE FROM care_event WHERE garden_id = $1
`

// Deletes the garden's care events before the garden itself, because
// care_event references care_type with ON DELETE RESTRICT and Postgres refuses
// the cascade while any event is left. Deleting the garden then cascades to
// its memberships, plants, care types, schedules, photos, invites and tokens.
func (q *Queries) DeleteGardenCareEvents(ctx context.Context, gardenID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGardenCareEvents, gardenID)
	return err
}

const getGarden = `-- name: GetGarden :one
SELECT id, name, created_at FROM garden WHERE id = $1
`

func (q *Queries) GetGarden(ctx context.Context, gardenID uuid.UUID) (Garden, error) {
	row := q.db.QueryRow(ctx, getGarden, gardenID)
	var i Garden
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getGardenOwner = `-- name: GetGardenOwner :one
SELECT app_user.id, app_user.display_name
FROM membership
JOIN app_user ON app_user.id = membership.user_id
WHERE membership.garden_id = $1 AND membership.role = 'owner'
ORDER BY membership.created_at, membership.id
LIMIT 1
`

type GetGardenOwnerRow struct {
	ID          uuid.UUID
	DisplayName string
}

// The garden's owner: the oldest owner membership, the person who created the
// garden unless they have left it. No row when no owner is left. A
// notification names another person's garden after its owner, "Ellie's
// Rosewood", and the owner's own garden by its name alone.
func (q *Queries) GetGardenOwner(ctx context.Context, gardenID uuid.UUID) (GetGardenOwnerRow, error) {
	row := q.db.QueryRow(ctx, getGardenOwner, gardenID)
	var i GetGardenOwnerRow
	err := row.Scan(&i.ID, &i.DisplayName)
	return i, err
}

const renameGarden = `-- name: RenameGarden :exec
UPDATE garden SET name = $1 WHERE id = $2
`

func (q *Queries) RenameGarden(ctx context.Context, name string, gardenID uuid.UUID) error {
	_, err := q.db.Exec(ctx, renameGarden, name, gardenID)
	return err
}
