// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: garden.sql

package store

import (
	"context"

	"uuid"
)

const createGarden = `-- name: CreateGarden :one
INSERT INTO garden (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateGarden(ctx context.Context, name string) (Garden, error) {
	row := q.db.QueryRow(ctx, createGarden, name)
	var i Garden
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getGarden = `-- name: GetGarden :one
SELECT id, name, created_at FROM garden WHERE id = $1
`

func (q *Queries) GetGarden(ctx context.Context, gardenID uuid.UUID) (Garden, error) {
	row := q.db.QueryRow(ctx, getGarden, gardenID)
	var i Garden
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const renameGarden = `-- name: RenameGarden :exec
UPDATE garden SET name = $1 WHERE id = $2
`

func (q *Queries) RenameGarden(ctx context.Context, name string, gardenID uuid.UUID) error {
	_, err := q.db.Exec(ctx, renameGarden, name, gardenID)
	return err
}
