// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: garden.sql

package store

import (
	"context"

	"uuid"
)

const renameGarden = `-- name: RenameGarden :exec
UPDATE garden SET name = $1 WHERE id = $2
`

func (q *Queries) RenameGarden(ctx context.Context, name string, gardenID uuid.UUID) error {
	_, err := q.db.Exec(ctx, renameGarden, name, gardenID)
	return err
}
