// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const countPendingInvites = `-- name: CountPendingInvites :one
SELECT count(*) FROM invite
WHERE garden_id = $1 AND user_id IS NULL AND redeemed_at IS NULL AND expires_at > $2
`

// An expired invite is not pending, so More's People row counts only the ones
// that can still be redeemed. A re-enrolment link is not counted either: it
// adds a device to somebody already in the garden, and their row is in the
// members list rather than in the Pending invites section.
func (q *Queries) CountPendingInvites(ctx context.Context, gardenID uuid.UUID, now time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvites, gardenID, now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invite (garden_id, token_hash, role, user_id, created_by, expires_at, membership_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, garden_id, token_hash, role, user_id, created_by, created_at, expires_at, redeemed_at, membership_expires_at
`

type CreateInviteParams struct {
	GardenID            uuid.UUID
	TokenHash           string
	Role                string
	UserID              *uuid.UUID
	CreatedBy           uuid.UUID
	ExpiresAt           time.Time
	MembershipExpiresAt *time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.GardenID,
		arg.TokenHash,
		arg.Role,
		arg.UserID,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MembershipExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.TokenHash,
		&i.Role,
		&i.UserID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.MembershipExpiresAt,
	)
	return i, err
}

const deletePendingInvite = `-- name: DeletePendingInvite :execrows
DELETE FROM invite
WHERE garden_id = $1 AND id = $2 AND redeemed_at IS NULL
`

// Revoking deletes the row. That is what makes the link stop working. A
// redeemed invite is not deleted here, because Revoke is only offered on rows
// nobody has opened.
func (q *Queries) DeletePendingInvite(ctx context.Context, gardenID uuid.UUID, inviteID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePendingInvite, gardenID, inviteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRedeemedAndExpiredInvites = `-- name: DeleteRedeemedAndExpiredInvites :execrows
DELETE FROM invite
WHERE (redeemed_at IS NOT NULL AND redeemed_at <= $1::timestamptz)
   OR (user_id IS NOT NULL AND redeemed_at IS NULL AND expires_at <= $1::timestamptz)
`

// DeleteRedeemedAndExpiredInvites deletes the invites no page lists once they
// are @before or older: a redeemed invite of either kind, and an expired
// sign-in link. An expired join invite is kept, because People lists it under
// Pending invites with a Revoke button.
func (q *Queries) DeleteRedeemedAndExpiredInvites(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRedeemedAndExpiredInvites, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReenrolmentInvites = `-- name: DeleteReenrolmentInvites :execrows
DELETE FROM invite
WHERE garden_id = $1 AND user_id = $2 AND redeemed_at IS NULL
`

// Every unredeemed re-enrolment link for one person. Issuing a new one deletes
// the old, because these rows are not in the Pending invites section and a
// link nobody can see is a link nobody can revoke.
func (q *Queries) DeleteReenrolmentInvites(ctx context.Context, gardenID uuid.UUID, userID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReenrolmentInvites, gardenID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserReenrolmentInvites = `-- name: DeleteUserReenrolmentInvites :exec
DELETE FROM invite
WHERE user_id = $1::uuid AND redeemed_at IS NULL
`

// Deletes the unredeemed re-enrolment invites made for this account, in every
// garden. A redeemed invite is kept as a record of the enrolment.
func (q *Queries) DeleteUserReenrolmentInvites(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserReenrolmentInvites, userID)
	return err
}

const getInviteByTokenHash = `-- name: GetInviteByTokenHash :one
SELECT invite.id, invite.garden_id, invite.token_hash, invite.role, invite.user_id, invite.created_by, invite.created_at, invite.expires_at, invite.redeemed_at, invite.membership_expires_at, garden.id, garden.name, garden.created_at, app_user.id, app_user.display_name, app_user.handle, app_user.timezone, app_user.created_at, app_user.last_garden_id, app_user.closed_at
FROM invite
JOIN garden ON garden.id = invite.garden_id
JOIN app_user ON app_user.id = invite.created_by
WHERE invite.token_hash = $1
`

type GetInviteByTokenHashRow struct {
	Invite  Invite
	Garden  Garden
	AppUser AppUser
}

// The invite for a token hash, with its garden and the account that created
// it. The page shows the garden's name and that account's display name. There
// is no garden_id parameter, because the token is what says which garden the
// link is for.
func (q *Queries) GetInviteByTokenHash(ctx context.Context, tokenHash string) (GetInviteByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInviteByTokenHash, tokenHash)
	var i GetInviteByTokenHashRow
	err := row.Scan(
		&i.Invite.ID,
		&i.Invite.GardenID,
		&i.Invite.TokenHash,
		&i.Invite.Role,
		&i.Invite.UserID,
		&i.Invite.CreatedBy,
		&i.Invite.CreatedAt,
		&i.Invite.ExpiresAt,
		&i.Invite.RedeemedAt,
		&i.Invite.MembershipExpiresAt,
		&i.Garden.ID,
		&i.Garden.Name,
		&i.Garden.CreatedAt,
		&i.AppUser.ID,
		&i.AppUser.DisplayName,
		&i.AppUser.Handle,
		&i.AppUser.Timezone,
		&i.AppUser.CreatedAt,
		&i.AppUser.LastGardenID,
		&i.AppUser.ClosedAt,
	)
	return i, err
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT id, garden_id, token_hash, role, user_id, created_by, created_at, expires_at, redeemed_at, membership_expires_at FROM invite
WHERE garden_id = $1 AND user_id IS NULL AND redeemed_at IS NULL
ORDER BY created_at DESC, id
`

// The Pending invites section on People. It holds invites to people who are
// not in the garden yet, the ones that have run out included, because an
// expired link is still a row somebody wants to clear away.
func (q *Queries) ListPendingInvites(ctx context.Context, gardenID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listPendingInvites, gardenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.GardenID,
			&i.TokenHash,
			&i.Role,
			&i.UserID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RedeemedAt,
			&i.MembershipExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemInvite = `-- name: RedeemInvite :execrows
UPDATE invite SET redeemed_at = $1::timestamptz
WHERE garden_id = $2 AND id = $3 AND redeemed_at IS NULL AND expires_at > $1
`

type RedeemInviteParams struct {
	Now      time.Time
	GardenID uuid.UUID
	InviteID uuid.UUID
}

// Sets redeemed_at on an invite that has not been redeemed and has not
// expired. The row count is zero when it had already been redeemed or had
// expired, so the caller reads the count to find out whether it was usable.
func (q *Queries) RedeemInvite(ctx context.Context, arg RedeemInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, redeemInvite, arg.Now, arg.GardenID, arg.InviteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
