// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const countWaitingInvites = `-- name: CountWaitingInvites :one
SELECT count(*) FROM invite
WHERE garden_id = $1 AND redeemed_at IS NULL AND expires_at > $2
`

// An invite that has expired is not waiting for anybody, so More's People row
// counts only the ones that can still be redeemed.
func (q *Queries) CountWaitingInvites(ctx context.Context, gardenID uuid.UUID, now time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitingInvites, gardenID, now)
	var count int64
	err := row.Scan(&count)
	return count, err
}
