// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package store

import (
	"context"

	"uuid"
)

const getMembershipWithUserAndGarden = `-- name: GetMembershipWithUserAndGarden :one
SELECT membership.id, membership.garden_id, membership.user_id, membership.role, membership.invited_by, membership.created_at, membership.expires_at, membership.digest_hour, app_user.id, app_user.display_name, app_user.handle, app_user.timezone, app_user.created_at, garden.id, garden.name, garden.created_at
FROM membership
JOIN app_user ON app_user.id = membership.user_id
JOIN garden ON garden.id = membership.garden_id
WHERE membership.garden_id = $1 AND membership.user_id = $2
`

type GetMembershipWithUserAndGardenRow struct {
	Membership Membership
	AppUser    AppUser
	Garden     Garden
}

// Runs on every authenticated request, so one join fetches all three rows in a
// single round trip.
func (q *Queries) GetMembershipWithUserAndGarden(ctx context.Context, gardenID uuid.UUID, userID uuid.UUID) (GetMembershipWithUserAndGardenRow, error) {
	row := q.db.QueryRow(ctx, getMembershipWithUserAndGarden, gardenID, userID)
	var i GetMembershipWithUserAndGardenRow
	err := row.Scan(
		&i.Membership.ID,
		&i.Membership.GardenID,
		&i.Membership.UserID,
		&i.Membership.Role,
		&i.Membership.InvitedBy,
		&i.Membership.CreatedAt,
		&i.Membership.ExpiresAt,
		&i.Membership.DigestHour,
		&i.AppUser.ID,
		&i.AppUser.DisplayName,
		&i.AppUser.Handle,
		&i.AppUser.Timezone,
		&i.AppUser.CreatedAt,
		&i.Garden.ID,
		&i.Garden.Name,
		&i.Garden.CreatedAt,
	)
	return i, err
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT id, garden_id, user_id, role, invited_by, created_at, expires_at, digest_hour FROM membership
WHERE user_id = $1
ORDER BY created_at, id
`

// A new session starts on the oldest membership. This takes no garden_id
// because it is how the garden is found. Every row returned belongs to
// @user_id.
func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.GardenID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.DigestHour,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
