// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const clearReminder = `-- name: ClearReminder :exec
UPDATE membership SET remind_again_at = NULL
WHERE garden_id = $1 AND id = $2 AND remind_again_at = $3
`

type ClearReminderParams struct {
	GardenID      uuid.UUID
	MembershipID  uuid.UUID
	RemindAgainAt *time.Time
}

// Clears the reminder the digest job is sending, in the transaction that
// sends it. The time is matched so that a later one the member set while the
// job was sending is kept.
func (q *Queries) ClearReminder(ctx context.Context, arg ClearReminderParams) error {
	_, err := q.db.Exec(ctx, clearReminder, arg.GardenID, arg.MembershipID, arg.RemindAgainAt)
	return err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO membership (garden_id, user_id, role, invited_by, expires_at, digest_hour)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, garden_id, user_id, role, invited_by, created_at, expires_at, digest_hour, remind_again_at
`

type CreateMembershipParams struct {
	GardenID   uuid.UUID
	UserID     uuid.UUID
	Role       string
	InvitedBy  *uuid.UUID
	ExpiresAt  *time.Time
	DigestHour int16
}

// CreateMembership inserts the membership row and returns it. The caller also
// writes the two notification_preference rows every membership has.
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.GardenID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
		arg.DigestHour,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DigestHour,
		&i.RemindAgainAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :execrows
DELETE FROM membership
WHERE garden_id = $1 AND user_id = $2
`

// Removing a member deletes the membership. The foreign key sets garden_id to
// NULL on their sessions for this garden, so they stay signed in. Every care
// event they logged stays where it is, because an event points at the account
// and not at the membership.
func (q *Queries) DeleteMembership(ctx context.Context, gardenID uuid.UUID, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMembership, gardenID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserMemberships = `-- name: DeleteUserMemberships :exec
DELETE FROM membership WHERE user_id = $1
`

// Deletes the account's memberships in every garden. There is no garden id
// because the query spans them all.
func (q *Queries) DeleteUserMemberships(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserMemberships, userID)
	return err
}

const getMemberByHandle = `-- name: GetMemberByHandle :one
SELECT membership.id, membership.garden_id, membership.user_id, membership.role, membership.invited_by, membership.created_at, membership.expires_at, membership.digest_hour, membership.remind_again_at, app_user.id, app_user.display_name, app_user.handle, app_user.timezone, app_user.created_at, app_user.last_garden_id, app_user.closed_at
FROM membership
JOIN app_user ON app_user.id = membership.user_id
WHERE membership.garden_id = $1 AND app_user.handle = $2
`

type GetMemberByHandleRow struct {
	Membership Membership
	AppUser    AppUser
}

// People names a member by handle in its URLs. A handle belonging to somebody
// outside the garden returns no row, so the route returns 404 for it.
func (q *Queries) GetMemberByHandle(ctx context.Context, gardenID uuid.UUID, handle string) (GetMemberByHandleRow, error) {
	row := q.db.QueryRow(ctx, getMemberByHandle, gardenID, handle)
	var i GetMemberByHandleRow
	err := row.Scan(
		&i.Membership.ID,
		&i.Membership.GardenID,
		&i.Membership.UserID,
		&i.Membership.Role,
		&i.Membership.InvitedBy,
		&i.Membership.CreatedAt,
		&i.Membership.ExpiresAt,
		&i.Membership.DigestHour,
		&i.Membership.RemindAgainAt,
		&i.AppUser.ID,
		&i.AppUser.DisplayName,
		&i.AppUser.Handle,
		&i.AppUser.Timezone,
		&i.AppUser.CreatedAt,
		&i.AppUser.LastGardenID,
		&i.AppUser.ClosedAt,
	)
	return i, err
}

const getMembershipWithUserAndGarden = `-- name: GetMembershipWithUserAndGarden :one
SELECT membership.id, membership.garden_id, membership.user_id, membership.role, membership.invited_by, membership.created_at, membership.expires_at, membership.digest_hour, membership.remind_again_at, app_user.id, app_user.display_name, app_user.handle, app_user.timezone, app_user.created_at, app_user.last_garden_id, app_user.closed_at, garden.id, garden.name, garden.created_at,
    ARRAY(SELECT role_capability.capability FROM role_capability
        WHERE role_capability.role = membership.role
        ORDER BY role_capability.capability)::text[] AS capabilities
FROM membership
JOIN app_user ON app_user.id = membership.user_id
JOIN garden ON garden.id = membership.garden_id
WHERE membership.garden_id = $1 AND membership.user_id = $2
`

type GetMembershipWithUserAndGardenRow struct {
	Membership   Membership
	AppUser      AppUser
	Garden       Garden
	Capabilities []string
}

// Returns the membership, the account, the garden and the role's capabilities
// in one round trip, because it runs on every signed-in request. The
// capabilities are not cached, so a row added to role_capability takes effect
// on the next request.
func (q *Queries) GetMembershipWithUserAndGarden(ctx context.Context, gardenID uuid.UUID, userID uuid.UUID) (GetMembershipWithUserAndGardenRow, error) {
	row := q.db.QueryRow(ctx, getMembershipWithUserAndGarden, gardenID, userID)
	var i GetMembershipWithUserAndGardenRow
	err := row.Scan(
		&i.Membership.ID,
		&i.Membership.GardenID,
		&i.Membership.UserID,
		&i.Membership.Role,
		&i.Membership.InvitedBy,
		&i.Membership.CreatedAt,
		&i.Membership.ExpiresAt,
		&i.Membership.DigestHour,
		&i.Membership.RemindAgainAt,
		&i.AppUser.ID,
		&i.AppUser.DisplayName,
		&i.AppUser.Handle,
		&i.AppUser.Timezone,
		&i.AppUser.CreatedAt,
		&i.AppUser.LastGardenID,
		&i.AppUser.ClosedAt,
		&i.Garden.ID,
		&i.Garden.Name,
		&i.Garden.CreatedAt,
		&i.Capabilities,
	)
	return i, err
}

const getRemindLaterState = `-- name: GetRemindLaterState :one
SELECT
    EXISTS (SELECT 1 FROM push_subscription WHERE push_subscription.user_id = $1) AS has_browser,
    EXISTS (SELECT 1 FROM notification_send
        JOIN membership ON membership.id = notification_send.membership_id
        WHERE membership.garden_id = $2 AND membership.id = $3
          AND notification_send.kind = 'digest' AND notification_send.send_key = $4) AS digest_sent
`

type GetRemindLaterStateParams struct {
	UserID       uuid.UUID
	GardenID     uuid.UUID
	MembershipID uuid.UUID
	SendKey      string
}

type GetRemindLaterStateRow struct {
	HasBrowser bool
	DigestSent bool
}

// Returns whether the member has a subscribed browser, and whether
// notification_send has their digest for @send_key, today's date in their
// timezone. Today offers Remind me later only when these allow it.
func (q *Queries) GetRemindLaterState(ctx context.Context, arg GetRemindLaterStateParams) (GetRemindLaterStateRow, error) {
	row := q.db.QueryRow(ctx, getRemindLaterState,
		arg.UserID,
		arg.GardenID,
		arg.MembershipID,
		arg.SendKey,
	)
	var i GetRemindLaterStateRow
	err := row.Scan(&i.HasBrowser, &i.DigestSent)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT membership.id, membership.garden_id, membership.user_id, membership.role, membership.invited_by, membership.created_at, membership.expires_at, membership.digest_hour, membership.remind_again_at, app_user.id, app_user.display_name, app_user.handle, app_user.timezone, app_user.created_at, app_user.last_garden_id, app_user.closed_at
FROM membership
JOIN app_user ON app_user.id = membership.user_id
WHERE membership.garden_id = $1
ORDER BY membership.created_at, membership.id
`

type ListMembersRow struct {
	Membership Membership
	AppUser    AppUser
}

// The People page lists everybody in the garden, oldest membership first, so
// the person who created it is at the top.
func (q *Queries) ListMembers(ctx context.Context, gardenID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, gardenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.Membership.ID,
			&i.Membership.GardenID,
			&i.Membership.UserID,
			&i.Membership.Role,
			&i.Membership.InvitedBy,
			&i.Membership.CreatedAt,
			&i.Membership.ExpiresAt,
			&i.Membership.DigestHour,
			&i.Membership.RemindAgainAt,
			&i.AppUser.ID,
			&i.AppUser.DisplayName,
			&i.AppUser.Handle,
			&i.AppUser.Timezone,
			&i.AppUser.CreatedAt,
			&i.AppUser.LastGardenID,
			&i.AppUser.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersWithCapability = `-- name: ListMembersWithCapability :many
SELECT membership.id, membership.garden_id, membership.user_id, membership.role, membership.invited_by, membership.created_at, membership.expires_at, membership.digest_hour, membership.remind_again_at, app_user.id, app_user.display_name, app_user.handle, app_user.timezone, app_user.created_at, app_user.last_garden_id, app_user.closed_at
FROM membership
JOIN app_user ON app_user.id = membership.user_id
JOIN role_capability ON role_capability.role = membership.role AND role_capability.capability = $1
WHERE membership.garden_id = $2
  AND (membership.expires_at IS NULL OR membership.expires_at > $3::timestamptz)
ORDER BY membership.created_at, membership.id
`

type ListMembersWithCapabilityParams struct {
	Capability string
	GardenID   uuid.UUID
	Now        time.Time
}

type ListMembersWithCapabilityRow struct {
	Membership Membership
	AppUser    AppUser
}

// The members of the garden whose role grants @capability and whose membership
// has not ended at @now, oldest membership first.
func (q *Queries) ListMembersWithCapability(ctx context.Context, arg ListMembersWithCapabilityParams) ([]ListMembersWithCapabilityRow, error) {
	rows, err := q.db.Query(ctx, listMembersWithCapability, arg.Capability, arg.GardenID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersWithCapabilityRow
	for rows.Next() {
		var i ListMembersWithCapabilityRow
		if err := rows.Scan(
			&i.Membership.ID,
			&i.Membership.GardenID,
			&i.Membership.UserID,
			&i.Membership.Role,
			&i.Membership.InvitedBy,
			&i.Membership.CreatedAt,
			&i.Membership.ExpiresAt,
			&i.Membership.DigestHour,
			&i.Membership.RemindAgainAt,
			&i.AppUser.ID,
			&i.AppUser.DisplayName,
			&i.AppUser.Handle,
			&i.AppUser.Timezone,
			&i.AppUser.CreatedAt,
			&i.AppUser.LastGardenID,
			&i.AppUser.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsForUser = `-- name: ListMembershipsForUser :many
SELECT membership.id, membership.garden_id, membership.user_id, membership.role, membership.invited_by, membership.created_at, membership.expires_at, membership.digest_hour, membership.remind_again_at FROM membership
JOIN app_user ON app_user.id = membership.user_id
WHERE membership.user_id = $1
ORDER BY membership.garden_id = app_user.last_garden_id DESC NULLS LAST, membership.created_at, membership.id
`

// The garden a session is put on is the first row here that has not ended.
// Rows come back with the garden the account last switched to first, then the
// oldest membership. This takes no garden_id because it is how the garden is
// found. Every row returned belongs to @user_id.
func (q *Queries) ListMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]Membership, error) {
	rows, err := q.db.Query(ctx, listMembershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membership
	for rows.Next() {
		var i Membership
		if err := rows.Scan(
			&i.ID,
			&i.GardenID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.DigestHour,
			&i.RemindAgainAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsWithGardensForUser = `-- name: ListMembershipsWithGardensForUser :many
SELECT membership.id, membership.garden_id, membership.user_id, membership.role, membership.invited_by, membership.created_at, membership.expires_at, membership.digest_hour, membership.remind_again_at, garden.id, garden.name, garden.created_at,
    coalesce(owner.display_name, '')::text AS owner_name,
    coalesce(owner.id = membership.user_id, false)::boolean AS reader_owns
FROM membership
JOIN garden ON garden.id = membership.garden_id
LEFT JOIN LATERAL (
    SELECT app_user.id, app_user.display_name
    FROM membership o
    JOIN app_user ON app_user.id = o.user_id
    WHERE o.garden_id = garden.id AND o.role = 'owner'
    ORDER BY o.created_at, o.id
    LIMIT 1
) AS owner ON true
WHERE membership.user_id = $1
ORDER BY membership.created_at, membership.id
`

type ListMembershipsWithGardensForUserRow struct {
	Membership Membership
	Garden     Garden
	OwnerName  string
	ReaderOwns bool
}

// Every garden the account is a member of, oldest membership first, with the
// owner's display name. The owner is the oldest owner membership: the person
// who created the garden, unless they have left it. owner_name is empty and
// reader_owns is false when no owner is left. This takes no garden_id because
// it is how the account's other gardens are found. Every row belongs to
// @user_id.
func (q *Queries) ListMembershipsWithGardensForUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsWithGardensForUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsWithGardensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsWithGardensForUserRow
	for rows.Next() {
		var i ListMembershipsWithGardensForUserRow
		if err := rows.Scan(
			&i.Membership.ID,
			&i.Membership.GardenID,
			&i.Membership.UserID,
			&i.Membership.Role,
			&i.Membership.InvitedBy,
			&i.Membership.CreatedAt,
			&i.Membership.ExpiresAt,
			&i.Membership.DigestHour,
			&i.Membership.RemindAgainAt,
			&i.Garden.ID,
			&i.Garden.Name,
			&i.Garden.CreatedAt,
			&i.OwnerName,
			&i.ReaderOwns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSittingDeadlines = `-- name: ListSittingDeadlines :many
SELECT sitting.id AS sitting_id, sitting.expires_at::timestamptz AS ends_at,
    sitter.display_name AS sitter_name, garden.name AS garden_name,
    recipient.id AS membership_id, recipient.user_id, app_user.handle,
    (recipient.id = sitting.id)::boolean AS is_sitter,
    coalesce(owner.display_name, '')::text AS owner_name,
    coalesce(owner.id = recipient.user_id, false)::boolean AS recipient_owns
FROM membership sitting
JOIN app_user sitter ON sitter.id = sitting.user_id
JOIN garden ON garden.id = sitting.garden_id
JOIN membership recipient ON recipient.garden_id = sitting.garden_id
    AND (recipient.id = sitting.id
        OR (recipient.user_id = sitting.invited_by AND (recipient.expires_at IS NULL OR recipient.expires_at > $1::timestamptz)))
JOIN app_user ON app_user.id = recipient.user_id
LEFT JOIN LATERAL (
    SELECT app_user.id, app_user.display_name
    FROM membership o
    JOIN app_user ON app_user.id = o.user_id
    WHERE o.garden_id = garden.id AND o.role = 'owner'
    ORDER BY o.created_at, o.id
    LIMIT 1
) AS owner ON true
WHERE sitting.expires_at IS NOT NULL AND sitting.expires_at > $2::timestamptz
  AND EXISTS (SELECT 1 FROM push_subscription WHERE push_subscription.user_id = recipient.user_id)
ORDER BY sitting.expires_at, sitting.id, recipient.id = sitting.id DESC
`

type ListSittingDeadlinesRow struct {
	SittingID     uuid.UUID
	EndsAt        time.Time
	SitterName    string
	GardenName    string
	MembershipID  uuid.UUID
	UserID        uuid.UUID
	Handle        string
	IsSitter      bool
	OwnerName     string
	RecipientOwns bool
}

// For every membership with an end date after @since: the sitter, and the
// person who invited them where that person is still a member at @now. One row
// per recipient, with is_sitter telling the two apart. A recipient with no
// browser subscribed is left out, so the job never claims a ledger row and then
// sends nothing. owner_name is the display name of the garden's owner, empty
// when the garden has no owner. recipient_owns is true when the recipient is
// that owner. There is no @garden_id because the job runs across every garden.
func (q *Queries) ListSittingDeadlines(ctx context.Context, now time.Time, since time.Time) ([]ListSittingDeadlinesRow, error) {
	rows, err := q.db.Query(ctx, listSittingDeadlines, now, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSittingDeadlinesRow
	for rows.Next() {
		var i ListSittingDeadlinesRow
		if err := rows.Scan(
			&i.SittingID,
			&i.EndsAt,
			&i.SitterName,
			&i.GardenName,
			&i.MembershipID,
			&i.UserID,
			&i.Handle,
			&i.IsSitter,
			&i.OwnerName,
			&i.RecipientOwns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeReminder = `-- name: RemoveReminder :execrows
UPDATE membership SET remind_again_at = NULL
WHERE garden_id = $1 AND user_id = $2
  AND remind_again_at > $3::timestamptz
`

type RemoveReminderParams struct {
	GardenID uuid.UUID
	UserID   uuid.UUID
	Now      time.Time
}

// Removes the waiting reminder. It returns 0 rows when no reminder is waiting
// after @now, because the job has already sent it.
func (q *Queries) RemoveReminder(ctx context.Context, arg RemoveReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeReminder, arg.GardenID, arg.UserID, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewMembership = `-- name: RenewMembership :one
UPDATE membership
SET role = $1, invited_by = $2, expires_at = $3
WHERE garden_id = $4 AND user_id = $5
RETURNING id, garden_id, user_id, role, invited_by, created_at, expires_at, digest_hour, remind_again_at
`

type RenewMembershipParams struct {
	Role      string
	InvitedBy *uuid.UUID
	ExpiresAt *time.Time
	GardenID  uuid.UUID
	UserID    uuid.UUID
}

// Accepting an invite as an account whose membership of the garden has ended
// updates that row rather than inserting one, because membership is unique on
// (garden_id, user_id). The row keeps its digest hour and its notification
// preferences.
func (q *Queries) RenewMembership(ctx context.Context, arg RenewMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, renewMembership,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
		arg.GardenID,
		arg.UserID,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.DigestHour,
		&i.RemindAgainAt,
	)
	return i, err
}

const rescheduleReminder = `-- name: RescheduleReminder :execrows
UPDATE membership SET remind_again_at = $1
WHERE garden_id = $2 AND user_id = $3
  AND remind_again_at > $4::timestamptz
`

type RescheduleReminderParams struct {
	RemindAgainAt *time.Time
	GardenID      uuid.UUID
	UserID        uuid.UUID
	Now           time.Time
}

// Moves the waiting reminder to a new time. It returns 0 rows when no reminder
// is waiting after @now, because the job has already sent it.
func (q *Queries) RescheduleReminder(ctx context.Context, arg RescheduleReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, rescheduleReminder,
		arg.RemindAgainAt,
		arg.GardenID,
		arg.UserID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDigestHour = `-- name: SetDigestHour :exec
UPDATE membership SET digest_hour = $1
WHERE garden_id = $2 AND user_id = $3
`

type SetDigestHourParams struct {
	DigestHour int16
	GardenID   uuid.UUID
	UserID     uuid.UUID
}

// The hour the digest arrives, which is per membership: a person may want one
// for their own garden and nothing from a garden they are sitting.
func (q *Queries) SetDigestHour(ctx context.Context, arg SetDigestHourParams) error {
	_, err := q.db.Exec(ctx, setDigestHour, arg.DigestHour, arg.GardenID, arg.UserID)
	return err
}

const setMemberRole = `-- name: SetMemberRole :execrows
UPDATE membership SET role = $1
WHERE garden_id = $2 AND user_id = $3
`

type SetMemberRoleParams struct {
	Role     string
	GardenID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) SetMemberRole(ctx context.Context, arg SetMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMemberRole, arg.Role, arg.GardenID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMembershipEnd = `-- name: SetMembershipEnd :execrows
UPDATE membership SET expires_at = $1
WHERE garden_id = $2 AND user_id = $3
`

type SetMembershipEndParams struct {
	ExpiresAt *time.Time
	GardenID  uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) SetMembershipEnd(ctx context.Context, arg SetMembershipEndParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMembershipEnd, arg.ExpiresAt, arg.GardenID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setReminder = `-- name: SetReminder :execrows
UPDATE membership SET remind_again_at = $1
WHERE garden_id = $2 AND user_id = $3
  AND (remind_again_at IS NULL OR remind_again_at <= $4::timestamptz)
`

type SetReminderParams struct {
	RemindAgainAt *time.Time
	GardenID      uuid.UUID
	UserID        uuid.UUID
	Now           time.Time
}

// Sets the time of a reminder from Remind me later on Today. It returns 0 rows
// when an earlier reminder is still waiting after @now, because a member has
// one waiting reminder at a time.
func (q *Queries) SetReminder(ctx context.Context, arg SetReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReminder,
		arg.RemindAgainAt,
		arg.GardenID,
		arg.UserID,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
