// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"uuid"
)

type APIToken struct {
	ID         uuid.UUID
	GardenID   uuid.UUID
	Name       string
	TokenHash  string
	Prefix     string
	CreatedBy  uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
}

type AppUser struct {
	ID           uuid.UUID
	DisplayName  string
	Handle       string
	Timezone     string
	CreatedAt    time.Time
	LastGardenID *uuid.UUID
	ClosedAt     *time.Time
}

type Capability struct {
	Name string
}

type CareEvent struct {
	ID                   uuid.UUID
	GardenID             uuid.UUID
	PlantID              uuid.UUID
	CareTypeID           uuid.UUID
	PerformedBy          uuid.UUID
	PerformedAt          time.Time
	RecordedAt           time.Time
	Done                 bool
	Note                 *string
	OverrideIntervalDays *int32
}

type CareSchedule struct {
	ID               uuid.UUID
	GardenID         uuid.UUID
	PlantID          uuid.UUID
	CareTypeID       uuid.UUID
	IntervalCount    *int32
	IntervalUnit     *string
	AnchorDate       *time.Time
	AnchorPrecision  *string
	SeasonStartMonth *int16
	SeasonEndMonth   *int16
	SetAt            time.Time
}

type CareType struct {
	ID         uuid.UUID
	GardenID   uuid.UUID
	Name       string
	Slug       string
	CreatedAt  time.Time
	ArchivedAt *time.Time
}

type Garden struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}

type Invite struct {
	ID                  uuid.UUID
	GardenID            uuid.UUID
	TokenHash           string
	Role                string
	UserID              *uuid.UUID
	CreatedBy           uuid.UUID
	CreatedAt           time.Time
	ExpiresAt           time.Time
	RedeemedAt          *time.Time
	MembershipExpiresAt *time.Time
}

type Membership struct {
	ID         uuid.UUID
	GardenID   uuid.UUID
	UserID     uuid.UUID
	Role       string
	InvitedBy  *uuid.UUID
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	DigestHour int16
}

type NotificationKind struct {
	Name string
}

type NotificationPreference struct {
	MembershipID uuid.UUID
	Kind         string
	Enabled      bool
}

type NotificationSend struct {
	MembershipID uuid.UUID
	Kind         string
	SendKey      string
	SentAt       time.Time
}

type PasskeyCredential struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	CredentialID string
	Name         string
	PublicKey    []byte
	SignCount    int64
	Flags        int16
	Transports   []string
	CreatedAt    time.Time
	LastUsedAt   *time.Time
}

type Photo struct {
	ID          uuid.UUID
	GardenID    uuid.UUID
	PlantID     uuid.UUID
	UploadedBy  uuid.UUID
	TakenAt     *time.Time
	UploadedAt  time.Time
	Kind        string
	Path        string
	Width       int32
	Height      int32
	Bytes       int64
	SquareBytes *int64
	FocusX      int16
	FocusY      int16
}

type Plant struct {
	ID             uuid.UUID
	GardenID       uuid.UUID
	Nickname       *string
	CommonName     *string
	BotanicalName  *string
	Location       *string
	Sun            *string
	WaterNeeds     *string
	FeedNeeds      *string
	Soil           *string
	Climate        *string
	Pot            *string
	Notes          *string
	AcquiredYear   *int16
	AcquiredMonth  *int16
	CreatedAt      time.Time
	ArchivedAt     *time.Time
	ProfilePhotoID *uuid.UUID
}

type PushSubscription struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Endpoint   string
	P256dhKey  string
	AuthKey    string
	UserAgent  *string
	CreatedAt  time.Time
	LastSentAt *time.Time
}

type RecoveryCode struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	CodeHash    string
	GeneratedAt time.Time
	UsedAt      *time.Time
}

type Role struct {
	Name string
	Rank int16
}

type RoleCapability struct {
	Role       string
	Capability string
}

type Session struct {
	ID                  uuid.UUID
	TokenHash           string
	UserID              uuid.UUID
	GardenID            *uuid.UUID
	PasskeyCredentialID *uuid.UUID
	UserAgent           *string
	CreatedAt           time.Time
	LastSeenAt          time.Time
}

type WebauthnCeremony struct {
	ID        uuid.UUID
	TokenHash string
	UserID    *uuid.UUID
	Session   []byte
	CreatedAt time.Time
	ExpiresAt time.Time
}
