// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_preference.sql

package store

import (
	"context"

	"uuid"
)

const listNotificationPreferences = `-- name: ListNotificationPreferences :many
SELECT membership_id, kind, enabled FROM notification_preference
WHERE membership_id = $1
ORDER BY kind
`

func (q *Queries) ListNotificationPreferences(ctx context.Context, membershipID uuid.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, listNotificationPreferences, membershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationPreference
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(&i.MembershipID, &i.Kind, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNotificationPreference = `-- name: SetNotificationPreference :exec
INSERT INTO notification_preference (membership_id, kind, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (membership_id, kind) DO UPDATE SET enabled = EXCLUDED.enabled
`

type SetNotificationPreferenceParams struct {
	MembershipID uuid.UUID
	Kind         string
	Enabled      bool
}

func (q *Queries) SetNotificationPreference(ctx context.Context, arg SetNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, setNotificationPreference, arg.MembershipID, arg.Kind, arg.Enabled)
	return err
}
