// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_send.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const claimNotificationSend = `-- name: ClaimNotificationSend :execrows
INSERT INTO notification_send (membership_id, kind, send_key)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type ClaimNotificationSendParams struct {
	MembershipID uuid.UUID
	Kind         string
	SendKey      string
}

// Returns 0 rows when the send is already in the ledger, so the caller sends
// nothing a second time.
func (q *Queries) ClaimNotificationSend(ctx context.Context, arg ClaimNotificationSendParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimNotificationSend, arg.MembershipID, arg.Kind, arg.SendKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDigestMembers = `-- name: ListDigestMembers :many
SELECT membership.id AS membership_id, membership.garden_id, membership.user_id, membership.digest_hour,
    app_user.handle, app_user.timezone, garden.name AS garden_name,
    coalesce((SELECT max(send_key) FROM notification_send
        WHERE notification_send.membership_id = membership.id AND notification_send.kind = 'digest'), '')::text AS sent_through
FROM membership
JOIN app_user ON app_user.id = membership.user_id
JOIN garden ON garden.id = membership.garden_id
JOIN notification_preference ON notification_preference.membership_id = membership.id
    AND notification_preference.kind = 'digest' AND notification_preference.enabled
WHERE (membership.expires_at IS NULL OR membership.expires_at > $1::timestamptz)
  AND EXISTS (SELECT 1 FROM push_subscription WHERE push_subscription.user_id = membership.user_id)
ORDER BY membership.created_at, membership.id
`

type ListDigestMembersRow struct {
	MembershipID uuid.UUID
	GardenID     uuid.UUID
	UserID       uuid.UUID
	DigestHour   int16
	Handle       string
	Timezone     string
	GardenName   string
	SentThrough  string
}

// Every membership the digest job may have to send to: the digest switched on,
// the membership not ended at @now, and at least one subscribed browser. A
// member with no browser is left out rather than having their day claimed with
// nothing sent, so a browser subscribed within the hour after their hour still
// gets that day's digest. sent_through is the latest send key in the ledger for
// the membership, or empty. There is no @garden_id because the job runs across
// every garden.
func (q *Queries) ListDigestMembers(ctx context.Context, now time.Time) ([]ListDigestMembersRow, error) {
	rows, err := q.db.Query(ctx, listDigestMembers, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDigestMembersRow
	for rows.Next() {
		var i ListDigestMembersRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.GardenID,
			&i.UserID,
			&i.DigestHour,
			&i.Handle,
			&i.Timezone,
			&i.GardenName,
			&i.SentThrough,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
