// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkey_credential.sql

package store

import (
	"context"

	"uuid"
)

const deletePasskey = `-- name: DeletePasskey :execrows
DELETE FROM passkey_credential AS k
WHERE k.user_id = $1 AND k.id = $2
  AND 1 < (SELECT count(*) FROM passkey_credential AS held WHERE held.user_id = k.user_id)
`

// The subselect refuses a delete that names the only credential the account
// has, since there is no password behind it and no self-service way back in.
// Two removals sent at the same moment can still empty the list: each one
// counts on its own snapshot and neither blocks the other.
func (q *Queries) DeletePasskey(ctx context.Context, userID uuid.UUID, passkeyID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskey, userID, passkeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT id, user_id, credential_id, name, public_key, sign_count, transports, created_at, last_used_at FROM passkey_credential
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListPasskeys(ctx context.Context, userID uuid.UUID) ([]PasskeyCredential, error) {
	rows, err := q.db.Query(ctx, listPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PasskeyCredential
	for rows.Next() {
		var i PasskeyCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.Name,
			&i.PublicKey,
			&i.SignCount,
			&i.Transports,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
