// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkey_credential.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createPasskey = `-- name: CreatePasskey :one
INSERT INTO passkey_credential (user_id, credential_id, name, public_key, sign_count, flags, transports)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, credential_id, name, public_key, sign_count, flags, transports, created_at, last_used_at
`

type CreatePasskeyParams struct {
	UserID       uuid.UUID
	CredentialID string
	Name         string
	PublicKey    []byte
	SignCount    int64
	Flags        int16
	Transports   []string
}

func (q *Queries) CreatePasskey(ctx context.Context, arg CreatePasskeyParams) (PasskeyCredential, error) {
	row := q.db.QueryRow(ctx, createPasskey,
		arg.UserID,
		arg.CredentialID,
		arg.Name,
		arg.PublicKey,
		arg.SignCount,
		arg.Flags,
		arg.Transports,
	)
	var i PasskeyCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.Name,
		&i.PublicKey,
		&i.SignCount,
		&i.Flags,
		&i.Transports,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deletePasskey = `-- name: DeletePasskey :execrows
DELETE FROM passkey_credential AS k
WHERE k.user_id = $1 AND k.id = $2
  AND 1 < (SELECT count(*) FROM passkey_credential AS held WHERE held.user_id = k.user_id)
`

// The subselect refuses a delete that names the only credential the account
// has, since there is no password behind it and no self-service way back in.
// The count comes from the statement's own snapshot, so two removals sent at
// the same moment would each count two and both go through. The caller locks
// the account's row in the same transaction first, so the second removal waits
// for the first to commit and counts one.
func (q *Queries) DeletePasskey(ctx context.Context, userID uuid.UUID, passkeyID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePasskey, userID, passkeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserPasskeys = `-- name: DeleteUserPasskeys :exec
DELETE FROM passkey_credential WHERE user_id = $1
`

// Deletes every passkey, including the last one. Removing passkeys one at a
// time stops at the last, because it is the only way to sign in. An account
// being closed is not going to sign in again.
func (q *Queries) DeleteUserPasskeys(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPasskeys, userID)
	return err
}

const getPasskeyByCredentialID = `-- name: GetPasskeyByCredentialID :one
SELECT k.id, k.user_id, k.credential_id, k.name, k.public_key, k.sign_count, k.flags, k.transports, k.created_at, k.last_used_at, u.id, u.display_name, u.handle, u.timezone, u.created_at, u.last_garden_id, u.closed_at
FROM passkey_credential AS k
JOIN app_user AS u ON u.id = k.user_id
WHERE k.credential_id = $1
`

type GetPasskeyByCredentialIDRow struct {
	PasskeyCredential PasskeyCredential
	AppUser           AppUser
}

// Sign-in has no username field, so the credential the browser returns is the
// only thing naming the account. The query returns that account row too.
func (q *Queries) GetPasskeyByCredentialID(ctx context.Context, credentialID string) (GetPasskeyByCredentialIDRow, error) {
	row := q.db.QueryRow(ctx, getPasskeyByCredentialID, credentialID)
	var i GetPasskeyByCredentialIDRow
	err := row.Scan(
		&i.PasskeyCredential.ID,
		&i.PasskeyCredential.UserID,
		&i.PasskeyCredential.CredentialID,
		&i.PasskeyCredential.Name,
		&i.PasskeyCredential.PublicKey,
		&i.PasskeyCredential.SignCount,
		&i.PasskeyCredential.Flags,
		&i.PasskeyCredential.Transports,
		&i.PasskeyCredential.CreatedAt,
		&i.PasskeyCredential.LastUsedAt,
		&i.AppUser.ID,
		&i.AppUser.DisplayName,
		&i.AppUser.Handle,
		&i.AppUser.Timezone,
		&i.AppUser.CreatedAt,
		&i.AppUser.LastGardenID,
		&i.AppUser.ClosedAt,
	)
	return i, err
}

const listPasskeys = `-- name: ListPasskeys :many
SELECT id, user_id, credential_id, name, public_key, sign_count, flags, transports, created_at, last_used_at FROM passkey_credential
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListPasskeys(ctx context.Context, userID uuid.UUID) ([]PasskeyCredential, error) {
	rows, err := q.db.Query(ctx, listPasskeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PasskeyCredential
	for rows.Next() {
		var i PasskeyCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.Name,
			&i.PublicKey,
			&i.SignCount,
			&i.Flags,
			&i.Transports,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :exec
SELECT id FROM app_user
WHERE id = $1
FOR UPDATE
`

// Locks the account's row until the transaction ends, so two writes that
// each depend on a count of the account's rows run one after the other.
func (q *Queries) LockUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockUser, userID)
	return err
}

const recordPasskeyUse = `-- name: RecordPasskeyUse :execrows
UPDATE passkey_credential
SET sign_count = $1, last_used_at = $2
WHERE id = $3
  AND (sign_count < $1 OR (sign_count = 0 AND $1 = 0))
`

type RecordPasskeyUseParams struct {
	SignCount int64
	UsedAt    *time.Time
	PasskeyID uuid.UUID
}

// The counter is compared in the statement that writes it, so two sign-ins
// sending the same counter cannot both pass: the second finds the row already
// advanced and updates nothing. Zero stored and zero returned is an
// authenticator that keeps no counter, and is the one equal pair allowed.
func (q *Queries) RecordPasskeyUse(ctx context.Context, arg RecordPasskeyUseParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordPasskeyUse, arg.SignCount, arg.UsedAt, arg.PasskeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
