// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO photo (id, garden_id, plant_id, uploaded_by, taken_at, kind, path, width, height, bytes, square_bytes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, garden_id, plant_id, uploaded_by, taken_at, uploaded_at, kind, path, width, height, bytes, square_bytes
`

type CreatePhotoParams struct {
	ID          uuid.UUID
	GardenID    uuid.UUID
	PlantID     uuid.UUID
	UploadedBy  uuid.UUID
	TakenAt     *time.Time
	Kind        string
	Path        string
	Width       int32
	Height      int32
	Bytes       int64
	SquareBytes *int64
}

// The id is supplied rather than defaulted, because the file is written under
// that id before the row exists.
func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (Photo, error) {
	row := q.db.QueryRow(ctx, createPhoto,
		arg.ID,
		arg.GardenID,
		arg.PlantID,
		arg.UploadedBy,
		arg.TakenAt,
		arg.Kind,
		arg.Path,
		arg.Width,
		arg.Height,
		arg.Bytes,
		arg.SquareBytes,
	)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.PlantID,
		&i.UploadedBy,
		&i.TakenAt,
		&i.UploadedAt,
		&i.Kind,
		&i.Path,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.SquareBytes,
	)
	return i, err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, garden_id, plant_id, uploaded_by, taken_at, uploaded_at, kind, path, width, height, bytes, square_bytes FROM photo
WHERE garden_id = $1 AND id = $2
`

func (q *Queries) GetPhoto(ctx context.Context, gardenID uuid.UUID, photoID uuid.UUID) (Photo, error) {
	row := q.db.QueryRow(ctx, getPhoto, gardenID, photoID)
	var i Photo
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.PlantID,
		&i.UploadedBy,
		&i.TakenAt,
		&i.UploadedAt,
		&i.Kind,
		&i.Path,
		&i.Width,
		&i.Height,
		&i.Bytes,
		&i.SquareBytes,
	)
	return i, err
}
