// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plant.sql

package store

import (
	"context"

	"uuid"
)

const getPlant = `-- name: GetPlant :one
SELECT id, garden_id, nickname, common_name, botanical_name, location, sun, water_needs, feed_needs, soil, climate, pot, notes, acquired_year, acquired_month, created_at, archived_at FROM plant
WHERE garden_id = $1 AND id = $2
`

func (q *Queries) GetPlant(ctx context.Context, gardenID uuid.UUID, plantID uuid.UUID) (Plant, error) {
	row := q.db.QueryRow(ctx, getPlant, gardenID, plantID)
	var i Plant
	err := row.Scan(
		&i.ID,
		&i.GardenID,
		&i.Nickname,
		&i.CommonName,
		&i.BotanicalName,
		&i.Location,
		&i.Sun,
		&i.WaterNeeds,
		&i.FeedNeeds,
		&i.Soil,
		&i.Climate,
		&i.Pot,
		&i.Notes,
		&i.AcquiredYear,
		&i.AcquiredMonth,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listPlants = `-- name: ListPlants :many
SELECT id, garden_id, nickname, common_name, botanical_name, location, sun, water_needs, feed_needs, soil, climate, pot, notes, acquired_year, acquired_month, created_at, archived_at FROM plant
WHERE garden_id = $1 AND archived_at IS NULL
ORDER BY location NULLS LAST, coalesce(nickname, common_name, botanical_name), id
`

// The order is the roster's, which groups by room and puts a plant with no
// room last. Two plants can agree on room and name, so id ends the ordering.
func (q *Queries) ListPlants(ctx context.Context, gardenID uuid.UUID) ([]Plant, error) {
	rows, err := q.db.Query(ctx, listPlants, gardenID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plant
	for rows.Next() {
		var i Plant
		if err := rows.Scan(
			&i.ID,
			&i.GardenID,
			&i.Nickname,
			&i.CommonName,
			&i.BotanicalName,
			&i.Location,
			&i.Sun,
			&i.WaterNeeds,
			&i.FeedNeeds,
			&i.Soil,
			&i.Climate,
			&i.Pot,
			&i.Notes,
			&i.AcquiredYear,
			&i.AcquiredMonth,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
