// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_subscription.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscription
WHERE user_id = $1 AND id = $2
`

func (q *Queries) DeletePushSubscription(ctx context.Context, userID uuid.UUID, subscriptionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscription, userID, subscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActivitySubscriptions = `-- name: ListActivitySubscriptions :many
SELECT push_subscription.id, push_subscription.user_id, push_subscription.endpoint, push_subscription.p256dh_key, push_subscription.auth_key, push_subscription.user_agent, push_subscription.created_at, push_subscription.last_sent_at, app_user.handle, garden.name AS garden_name
FROM membership
JOIN app_user ON app_user.id = membership.user_id
JOIN garden ON garden.id = membership.garden_id
JOIN notification_preference ON notification_preference.membership_id = membership.id
    AND notification_preference.kind = 'activity' AND notification_preference.enabled
JOIN push_subscription ON push_subscription.user_id = membership.user_id
WHERE membership.garden_id = $1
  AND membership.user_id <> $2
  AND (membership.expires_at IS NULL OR membership.expires_at > $3::timestamptz)
ORDER BY membership.created_at, membership.id, push_subscription.created_at, push_subscription.id
`

type ListActivitySubscriptionsParams struct {
	GardenID uuid.UUID
	ActorID  uuid.UUID
	Now      time.Time
}

type ListActivitySubscriptionsRow struct {
	PushSubscription PushSubscription
	Handle           string
	GardenName       string
}

// The browsers to notify when @actor_id logs care in the garden: every push
// subscription of every other member whose membership has not ended and who
// has the activity notification on.
func (q *Queries) ListActivitySubscriptions(ctx context.Context, arg ListActivitySubscriptionsParams) ([]ListActivitySubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listActivitySubscriptions, arg.GardenID, arg.ActorID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivitySubscriptionsRow
	for rows.Next() {
		var i ListActivitySubscriptionsRow
		if err := rows.Scan(
			&i.PushSubscription.ID,
			&i.PushSubscription.UserID,
			&i.PushSubscription.Endpoint,
			&i.PushSubscription.P256dhKey,
			&i.PushSubscription.AuthKey,
			&i.PushSubscription.UserAgent,
			&i.PushSubscription.CreatedAt,
			&i.PushSubscription.LastSentAt,
			&i.Handle,
			&i.GardenName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT id, user_id, endpoint, p256dh_key, auth_key, user_agent, created_at, last_sent_at FROM push_subscription
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListPushSubscriptions(ctx context.Context, userID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dhKey,
			&i.AuthKey,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPushSubscriptionSent = `-- name: SetPushSubscriptionSent :exec
UPDATE push_subscription SET last_sent_at = $1
WHERE user_id = $2 AND id = $3
`

type SetPushSubscriptionSentParams struct {
	SentAt         *time.Time
	UserID         uuid.UUID
	SubscriptionID uuid.UUID
}

func (q *Queries) SetPushSubscriptionSent(ctx context.Context, arg SetPushSubscriptionSentParams) error {
	_, err := q.db.Exec(ctx, setPushSubscriptionSent, arg.SentAt, arg.UserID, arg.SubscriptionID)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscription (user_id, endpoint, p256dh_key, auth_key, user_agent)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    p256dh_key = EXCLUDED.p256dh_key,
    auth_key = EXCLUDED.auth_key,
    user_agent = EXCLUDED.user_agent,
    created_at = CASE WHEN push_subscription.user_id = EXCLUDED.user_id THEN push_subscription.created_at ELSE now() END,
    last_sent_at = CASE WHEN push_subscription.user_id = EXCLUDED.user_id THEN push_subscription.last_sent_at END
`

type UpsertPushSubscriptionParams struct {
	UserID    uuid.UUID
	Endpoint  string
	P256dhKey string
	AuthKey   string
	UserAgent *string
}

// The endpoint identifies the browser, so a browser subscribing again updates
// its row instead of adding one. A row that belonged to another account moves
// to the account signed in now. Its created_at and last_sent_at are reset,
// because those dates were the other account's.
func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dhKey,
		arg.AuthKey,
		arg.UserAgent,
	)
	return err
}
