// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_subscription.sql

package store

import (
	"context"

	"uuid"
)

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscription
WHERE user_id = $1 AND id = $2
`

func (q *Queries) DeletePushSubscription(ctx context.Context, userID uuid.UUID, subscriptionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscription, userID, subscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT id, user_id, endpoint, p256dh_key, auth_key, user_agent, created_at, last_sent_at FROM push_subscription
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListPushSubscriptions(ctx context.Context, userID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dhKey,
			&i.AuthKey,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
