// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_subscription.sql

package store

import (
	"context"

	"uuid"
)

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscription
WHERE user_id = $1 AND id = $2
`

func (q *Queries) DeletePushSubscription(ctx context.Context, userID uuid.UUID, subscriptionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscription, userID, subscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT id, user_id, endpoint, p256dh_key, auth_key, user_agent, created_at, last_sent_at FROM push_subscription
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListPushSubscriptions(ctx context.Context, userID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dhKey,
			&i.AuthKey,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :exec
INSERT INTO push_subscription (user_id, endpoint, p256dh_key, auth_key, user_agent)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE SET
    user_id = EXCLUDED.user_id,
    p256dh_key = EXCLUDED.p256dh_key,
    auth_key = EXCLUDED.auth_key,
    user_agent = EXCLUDED.user_agent,
    created_at = CASE WHEN push_subscription.user_id = EXCLUDED.user_id THEN push_subscription.created_at ELSE now() END,
    last_sent_at = CASE WHEN push_subscription.user_id = EXCLUDED.user_id THEN push_subscription.last_sent_at END
`

type UpsertPushSubscriptionParams struct {
	UserID    uuid.UUID
	Endpoint  string
	P256dhKey string
	AuthKey   string
	UserAgent *string
}

// The endpoint identifies the browser, so a browser subscribing again updates
// its row instead of adding one. A row that belonged to another account moves
// to the account signed in now. Its created_at and last_sent_at are reset,
// because those dates were the other account's.
func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dhKey,
		arg.AuthKey,
		arg.UserAgent,
	)
	return err
}
