// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_code.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const getRecoveryBatch = `-- name: GetRecoveryBatch :one
SELECT count(*)                                AS size,
       count(*) FILTER (WHERE used_at IS NULL) AS unused,
       max(generated_at)::timestamptz          AS made_at
FROM recovery_code
WHERE user_id = $1
HAVING count(*) > 0
`

type GetRecoveryBatchRow struct {
	Size   int64
	Unused int64
	MadeAt time.Time
}

// Counts an account's recovery codes and reports when they were made, for the
// Recovery codes page. Codes are made and replaced as a whole batch, so every
// row a user has belongs to the same batch and shares its generated_at. An
// account with no codes gets no row back, rather than a row of zeroes with a
// null date. An account whose codes have all been used still gets a row, and
// the page reads "0 of 10 left".
func (q *Queries) GetRecoveryBatch(ctx context.Context, userID uuid.UUID) (GetRecoveryBatchRow, error) {
	row := q.db.QueryRow(ctx, getRecoveryBatch, userID)
	var i GetRecoveryBatchRow
	err := row.Scan(&i.Size, &i.Unused, &i.MadeAt)
	return i, err
}
