// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role_capability.sql

package store

import (
	"context"
)

const listRoleCapabilities = `-- name: ListRoleCapabilities :many
SELECT capability FROM role_capability
WHERE role = $1
ORDER BY capability
`

// Read on every request rather than cached, so a row added to the table takes
// effect on the next request.
func (q *Queries) ListRoleCapabilities(ctx context.Context, role string) ([]string, error) {
	rows, err := q.db.Query(ctx, listRoleCapabilities, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var capability string
		if err := rows.Scan(&capability); err != nil {
			return nil, err
		}
		items = append(items, capability)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
