// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (token_hash, user_id, garden_id, user_agent, created_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $5)
RETURNING id, token_hash, user_id, garden_id, user_agent, created_at, last_seen_at
`

type CreateSessionParams struct {
	TokenHash string
	UserID    uuid.UUID
	GardenID  uuid.UUID
	UserAgent *string
	Now       time.Time
}

// The instants are written from the caller's clock rather than the database's,
// so the expiry decision in Go compares two readings of one clock.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.GardenID,
		arg.UserAgent,
		arg.Now,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.GardenID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, token_hash, user_id, garden_id, user_agent, created_at, last_seen_at FROM session
WHERE token_hash = $1
`

// The session row is what tells a request which garden it is on, so this query
// cannot take a garden as an input and reads by the hash of the token instead.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.GardenID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :one
UPDATE session
SET last_seen_at = $1
WHERE token_hash = $2
RETURNING id, token_hash, user_id, garden_id, user_agent, created_at, last_seen_at
`

// The expiry check runs in Go before this query, so an expired row is deleted
// rather than revived.
func (q *Queries) TouchSession(ctx context.Context, lastSeenAt time.Time, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, touchSession, lastSeenAt, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.GardenID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
