// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (token_hash, user_id, garden_id, passkey_credential_id, user_agent, created_at, last_seen_at)
VALUES ($1, $2, $3, $4, $5, $6, $6)
RETURNING id, token_hash, user_id, garden_id, passkey_credential_id, user_agent, created_at, last_seen_at
`

type CreateSessionParams struct {
	TokenHash           string
	UserID              uuid.UUID
	GardenID            uuid.UUID
	PasskeyCredentialID *uuid.UUID
	UserAgent           *string
	Now                 time.Time
}

// Timestamps come from the caller's clock rather than now(), so the expiry
// check in Go compares two readings of the same clock.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.GardenID,
		arg.PasskeyCredentialID,
		arg.UserAgent,
		arg.Now,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.GardenID,
		&i.PasskeyCredentialID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, token_hash, user_id, garden_id, passkey_credential_id, user_agent, created_at, last_seen_at FROM session
WHERE token_hash = $1
`

// The session row is how a request learns its garden, so this query cannot
// take a garden_id. It reads by token hash instead.
func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.GardenID,
		&i.PasskeyCredentialID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const setSessionGarden = `-- name: SetSessionGarden :execrows
UPDATE session
SET garden_id = $1
WHERE token_hash = $2
`

// Switching gardens updates the session row rather than creating a new one, so
// the cookie stays as it is. The foreign key on (garden_id, user_id) rejects a
// garden the session's user is not a member of.
func (q *Queries) SetSessionGarden(ctx context.Context, gardenID uuid.UUID, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, setSessionGarden, gardenID, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :one
UPDATE session
SET last_seen_at = $1
WHERE token_hash = $2
RETURNING id, token_hash, user_id, garden_id, passkey_credential_id, user_agent, created_at, last_seen_at
`

// The caller checks expiry in Go before calling this, so an expired row is
// deleted rather than refreshed.
func (q *Queries) TouchSession(ctx context.Context, lastSeenAt time.Time, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, touchSession, lastSeenAt, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.GardenID,
		&i.PasskeyCredentialID,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
