// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup_link.sql

package store

import (
	"context"
	"time"
)

const createSetupLink = `-- name: CreateSetupLink :one
INSERT INTO setup_link (token_hash, expires_at)
VALUES ($1, $2)
RETURNING id, token_hash, created_at, expires_at, used_at
`

func (q *Queries) CreateSetupLink(ctx context.Context, tokenHash string, expiresAt time.Time) (SetupLink, error) {
	row := q.db.QueryRow(ctx, createSetupLink, tokenHash, expiresAt)
	var i SetupLink
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteUsedAndExpiredSetupLinks = `-- name: DeleteUsedAndExpiredSetupLinks :execrows
DELETE FROM setup_link
WHERE (used_at IS NOT NULL AND used_at <= $1::timestamptz)
   OR (used_at IS NULL AND expires_at <= $1::timestamptz)
`

// Deletes a used link whose used_at is at or before @before, and an unused
// link whose expires_at is.
func (q *Queries) DeleteUsedAndExpiredSetupLinks(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUsedAndExpiredSetupLinks, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setupLinkOpen = `-- name: SetupLinkOpen :one
SELECT EXISTS (
    SELECT 1 FROM setup_link
    WHERE token_hash = $1 AND used_at IS NULL AND expires_at > $2::timestamptz
)
`

// Reports whether the link with this token hash is unused and has not expired.
// A used, expired and unknown token all return false.
func (q *Queries) SetupLinkOpen(ctx context.Context, tokenHash string, now time.Time) (bool, error) {
	row := q.db.QueryRow(ctx, setupLinkOpen, tokenHash, now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const useSetupLink = `-- name: UseSetupLink :execrows
UPDATE setup_link SET used_at = $1::timestamptz
WHERE token_hash = $2 AND used_at IS NULL AND expires_at > $1
`

// Sets used_at on a link that is unused and has not expired. It updates no row
// for a used, expired or unknown token.
func (q *Queries) UseSetupLink(ctx context.Context, now time.Time, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, useSetupLink, now, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
