// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webauthn_ceremony.sql

package store

import (
	"context"
	"time"

	"uuid"
)

const createCeremony = `-- name: CreateCeremony :one
INSERT INTO webauthn_ceremony (token_hash, user_id, session, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, token_hash, user_id, session, created_at, expires_at
`

type CreateCeremonyParams struct {
	TokenHash string
	UserID    *uuid.UUID
	Session   []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateCeremony(ctx context.Context, arg CreateCeremonyParams) (WebauthnCeremony, error) {
	row := q.db.QueryRow(ctx, createCeremony,
		arg.TokenHash,
		arg.UserID,
		arg.Session,
		arg.ExpiresAt,
	)
	var i WebauthnCeremony
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.Session,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredCeremonies = `-- name: DeleteExpiredCeremonies :exec
DELETE FROM webauthn_ceremony WHERE expires_at <= $1
`

// A prompt nobody answers keeps its row until it expires, so this runs whenever
// a ceremony starts.
func (q *Queries) DeleteExpiredCeremonies(ctx context.Context, now time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredCeremonies, now)
	return err
}

const deleteUserCeremonies = `-- name: DeleteUserCeremonies :exec
DELETE FROM webauthn_ceremony WHERE user_id = $1::uuid
`

func (q *Queries) DeleteUserCeremonies(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserCeremonies, userID)
	return err
}

const takeCeremony = `-- name: TakeCeremony :one
DELETE FROM webauthn_ceremony
WHERE token_hash = $1 AND expires_at > $2
RETURNING id, token_hash, user_id, session, created_at, expires_at
`

// Deleting and returning in one statement is what makes a challenge answerable
// once. Two requests sending the same cookie race for the row and only one of
// them gets it.
func (q *Queries) TakeCeremony(ctx context.Context, tokenHash string, now time.Time) (WebauthnCeremony, error) {
	row := q.db.QueryRow(ctx, takeCeremony, tokenHash, now)
	var i WebauthnCeremony
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.Session,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
